### ISSUE TITLE
LoadError: incompatible library version gems/nokogiri-1.8.1

### ISSUE THREAD

**Issue by edusantana** [edusantana/indeva-lojas#4]
Obtive o seguinte erro:

```
rake aborted!
LoadError: incompatible library version - /home/dudu/.rvm/gems/ruby-2.4.1/gems/nokogiri-1.8.1/lib/nokogiri/nokogiri.so
/home/dudu/.rvm/gems/ruby-2.4.1/gems/nokogiri-1.8.1/lib/nokogiri.rb:32:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/nokogiri-1.8.1/lib/nokogiri.rb:32:in `rescue in <top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/nokogiri-1.8.1/lib/nokogiri.rb:28:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/loofah-2.1.1/lib/loofah.rb:3:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/loofah-2.1.1/lib/loofah.rb:3:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/rails-html-sanitizer-1.0.3/lib/rails-html-sanitizer.rb:2:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/rails-html-sanitizer-1.0.3/lib/rails-html-sanitizer.rb:2:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/sanitize_helper.rb:2:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/sanitize_helper.rb:2:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/text_helper.rb:32:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/text_helper.rb:32:in `<module:TextHelper>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/text_helper.rb:29:in `<module:Helpers>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/text_helper.rb:6:in `<module:ActionView>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/text_helper.rb:4:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/form_tag_helper.rb:18:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/form_tag_helper.rb:18:in `<module:FormTagHelper>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/form_tag_helper.rb:14:in `<module:Helpers>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/form_tag_helper.rb:8:in `<module:ActionView>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/form_tag_helper.rb:6:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/form_helper.rb:4:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/form_helper.rb:4:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers.rb:50:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers.rb:50:in `<module:Helpers>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers.rb:4:in `<module:ActionView>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers.rb:3:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/sprockets-rails-3.2.1/lib/sprockets/rails/context.rb:1:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/sprockets-rails-3.2.1/lib/sprockets/rails/context.rb:1:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:7:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:7:in `<top (required)>'
/home/alexandre/w/indeva/indeva-lojas/config/application.rb:12:in `require'
/home/alexandre/w/indeva/indeva-lojas/config/application.rb:12:in `<top (required)>'
/home/alexandre/w/indeva/indeva-lojas/Rakefile:4:in `require_relative'
/home/alexandre/w/indeva/indeva-lojas/Rakefile:4:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'

Caused by:
LoadError: cannot load such file -- nokogiri/2.3/nokogiri
/home/dudu/.rvm/gems/ruby-2.4.1/gems/nokogiri-1.8.1/lib/nokogiri.rb:30:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/nokogiri-1.8.1/lib/nokogiri.rb:30:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/loofah-2.1.1/lib/loofah.rb:3:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/loofah-2.1.1/lib/loofah.rb:3:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/rails-html-sanitizer-1.0.3/lib/rails-html-sanitizer.rb:2:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/rails-html-sanitizer-1.0.3/lib/rails-html-sanitizer.rb:2:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/sanitize_helper.rb:2:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/sanitize_helper.rb:2:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/text_helper.rb:32:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/text_helper.rb:32:in `<module:TextHelper>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/text_helper.rb:29:in `<module:Helpers>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/text_helper.rb:6:in `<module:ActionView>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/text_helper.rb:4:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/form_tag_helper.rb:18:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/form_tag_helper.rb:18:in `<module:FormTagHelper>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/form_tag_helper.rb:14:in `<module:Helpers>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/form_tag_helper.rb:8:in `<module:ActionView>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/form_tag_helper.rb:6:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/form_helper.rb:4:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers/form_helper.rb:4:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers.rb:50:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers.rb:50:in `<module:Helpers>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers.rb:4:in `<module:ActionView>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/actionview-5.1.4/lib/action_view/helpers.rb:3:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/sprockets-rails-3.2.1/lib/sprockets/rails/context.rb:1:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/sprockets-rails-3.2.1/lib/sprockets/rails/context.rb:1:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:7:in `require'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/sprockets-rails-3.2.1/lib/sprockets/railtie.rb:7:in `<top (required)>'
/home/alexandre/w/indeva/indeva-lojas/config/application.rb:12:in `require'
/home/alexandre/w/indeva/indeva-lojas/config/application.rb:12:in `<top (required)>'
/home/alexandre/w/indeva/indeva-lojas/Rakefile:4:in `require_relative'
/home/alexandre/w/indeva/indeva-lojas/Rakefile:4:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

**Comment by edusantana** [comment]
Estou perdendo muito tempo com esse problema, por isso que a solução com docker poderia ser tão promissora.

**Comment by edusantana** [comment]
Complicado...

```
dudu@eduardo-u16:~/w/indeva/indeva-lojas$ bundle exec rake -T
Your Ruby version is 2.3.1, but your Gemfile specified 2.4.1
dudu@eduardo-u16:~/w/indeva/indeva-lojas$ ruby --version
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
dudu@eduardo-u16:~/w/indeva/indeva-lojas$ rake -T
Your Ruby version is 2.3.1, but your Gemfile specified 2.4.1
```

**Comment by edusantana** [comment]
Depois de pagar todos os rubys e gems, instalar o ruby novamente, obtive o seguinte erro:

$ rake -T
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x000000018ecb68>
/home/dudu/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.0.4/lib/rspec/core/rake_task.rb:101:in `define'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/rspec-core-3.0.4/lib/rspec/core/rake_task.rb:78:in `initialize'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/rspec-rails-3.0.2/lib/rspec/rails/tasks/rspec.rake:11:in `new'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/rspec-rails-3.0.2/lib/rspec/rails/tasks/rspec.rake:11:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/rspec-rails-3.0.2/lib/rspec-rails.rb:13:in `load'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/rspec-rails-3.0.2/lib/rspec-rails.rb:13:in `block in <class:Railtie>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/railtie.rb:241:in `instance_exec'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/railtie.rb:241:in `block in run_tasks_blocks'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/railtie.rb:250:in `each'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/railtie.rb:250:in `each_registered_block'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/railtie.rb:241:in `run_tasks_blocks'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/application.rb:439:in `block in run_tasks_blocks'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/engine/railties.rb:13:in `each'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/engine/railties.rb:13:in `each'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/application.rb:439:in `run_tasks_blocks'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/railties-5.1.4/lib/rails/engine.rb:457:in `load_tasks'
/home/alexandre/w/indeva/indeva-lojas/Rakefile:6:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/home/dudu/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/home/dudu/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)

**Comment by edusantana** [comment]
Atualizei a versão do rspec

**Comment by edusantana** [comment]
https://github.com/rspec/rspec-core/pull/2197
